#!/usr/local/bin/ansible-playbook --inventory=inventory

- name: ' Operators '
  hosts: localhost
  vars_files:
    - vars/global.yml
  vars_prompt:
    - name: quay_json
      prompt: Enter your Quay pull secret?
      private: no

  tasks:
    - name: Create auth directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /root/.docker
        - /root/.kube

    - name: Create quay secret
      template:
        src: templates/quay.json
        dest: manifests/quay.json

    - name: Create registry secret
      template:
        src: templates/auth.json
        dest: manifests/local.json

    - name: Create full auth chain
      shell: "jq -s '.[0] * .[1]' manifests/local.json manifests/quay.json > manifests/auth.json"

    - name: Create auth file
      template:
        src: manifests/auth.json
        dest: /root/.docker/auth.json

    - name: Create auth file
      template:
        src: files/kubeconfig
        dest: /root/.kube/config

    - name: Create mapping.txt
      template:
        src: templates/custom-mapping.j2
        dest: manifests/custom-mapping.txt

    - name: Mirror custom catalog images
      shell: oc image mirror \
        --force \
        --filter-by-os=.* \
        --keep-manifest-list=true \
        --registry-config {{ quay_auth }} \
        -f manifests/custom-mapping.txt \
        --insecure
