#!/usr/local/bin/ansible-playbook --inventory=inventory

- name: ' Operators '
  hosts: local
  vars_files:
    - vars/global.yml

  tasks:
    - name: Create auth directory
      file:
        path: /root/.docker
        state: directory

    - name: Create auth file
      template:
        src: templates/auth.json
        dest: /root/.docker/auth.json

    - name: Create mapping.txt
      template:
        src: templates/custom-mapping.j2
        dest: manifests/custom-mapping.txt

    - name: Mirror custom catalog images
      shell: oc adm catalog mirror \
        --force \
        --filter-by-os=.* \
        --keep-manifest-list=true \
        --registry-config {{ quay_auth }} \
        -f manifests/custom-custom-mapping.txt \
        --insecure