#!/usr/local/bin/ansible-playbook --inventory=inventory

- name: ' Operators '
  hosts: local
  vars_files:
    - vars/global.yml

  tasks:
    - name: Create auth directory
      file:
        path: /root/.docker
        state: directory

    - name: Create auth file
      template:
        src: templates/auth.json
        dest: /root/.docker/auth.json

    - name: build Redhat catalog
      shell: oc adm catalog build \
        --appregistry-org redhat-operators \
        --from={{ redhat_operators }} \
        --filter-by-os="linux/amd64" \
        --to={{ local_registry }}/{{ local_redhat_catalog }} \
        -a {{ quay_auth }} \
        --insecure

    - name: build community catalog
      shell: oc adm catalog build \
        --appregistry-org community-operators \
        --from={{ community_operators }} \
        --filter-by-os="linux/amd64" \
        --to={{ local_registry }}/{{ local_community_catalog }} \
        -a {{ quay_auth }} \
        --insecure

    - name: Mirror Redhat catalog
      shell: oc adm catalog mirror \
        {{ local_registry }}/{{ local_redhat_catalog }} \
        {{ local_registry }} \
        -a {{ quay_auth }} \
        --insecure

    - name: Mirror community catalog
      shell: oc adm catalog mirror \
        {{ local_registry }}/{{ local_community_catalog }} \
        {{ local_registry }} \
        -a {{ quay_auth }} \
        --insecure